### ISSUE TITLE
[Xperia X] Display density

### ISSUE THREAD

**Issue by Frzifus** [fravaccaro/sailfishos-uithemer#2]
Its not possible to change the display pixel ratio.

Device: Xperia X
Build: 2.1.3.7

**Comment by fravaccaro** [comment]
I can't test it on a Sailfish X device right now, but I'll do it asap.

I reopened this issue as reference, this is a known bug.

**Comment by fravaccaro** [comment]
Added to Themepacksupport 0.5.6.
